---
# Name: nsq
# Version: latest
# FileVersion: 20191217
# Ref: 
#   - https://nsq.io/overview/quick_start.html
#   - https://nsq.io/deployment/docker.html

# Dockerfile
# 


# ####################################
# 环境变量
# ####################################


# ####################################
# 文件映射
# ####################################

version: '3'
services:
  # nsq-01:
  #   # command: /bin/bash
  #   restart: always
  #   build:
  #     context: ${BUILD_CONTEXT_DIR}
  #     dockerfile: ./stub/Dockerfile
  #   image: ${NSQ_IMG_TAG}
  #   hostname: nsq-01
  #   container_name: nsq-01
  #   volumes:
  #     - ./data:/data
  #     - ./conf/sv/nsq-server.ini:/etc/supervisord.d/nsq-server.ini
  #     - ./demo:/demo
  #     - ../../../../log/nsq/nsq-01:/var/log/nsq
  #     - ../../../..:/project
  #   ports:
  #     - "52201:22"
  #     - "8500:8500"

  # nsq-02:
  #   privileged: true
  #   restart: always
  #   image: ${NSQ_IMG_TAG}
  #   hostname: nsq-02
  #   container_name: nsq-02
  #   volumes:
  #     - ./data:/data
  #     - ./conf/sv/nsq-node.ini:/etc/supervisord.d/nsq-node.ini
  #     - ./demo:/demo
  #     - ../../../../log/nsq/nsq-02:/var/log/nsq
  #     - ../../../..:/project
  #   ports:
  #     - "52202:22"

  # nsq-03:
  #   privileged: true
  #   restart: always
  #   image: ${NSQ_IMG_TAG}
  #   hostname: nsq-03
  #   container_name: nsq-03
  #   volumes:
  #     - ./data:/data
  #     - ./conf/sv/nsq-node.ini:/etc/supervisord.d/nsq-node.ini
  #     - ./demo:/demo
  #     - ../../../../log/nsq/nsq-03:/var/log/nsq
  #     - ../../../..:/project
  #   ports:
  #     - "52203:22"

